/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupgenerator;

import javax.swing.JOptionPane;

/**
 * Students Display GUI
 * @author 23781271
 */
public class StudentsMenu extends javax.swing.JFrame {

    /**
     * Creates new form StudentsMenu
     */
    public StudentsMenu() {
        initComponents();
    }
    /**
     * Refreshes the Lists displayed on the GUI when a student is deleted
     */
    private void refreshLists() {
        reqDesignList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = GroupGenerator.students.getDesignReqNames();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        implementTestList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = GroupGenerator.students.getImplementTestNames();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        docMaintainList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = GroupGenerator.students.getDocMaintainNames();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reqDesignList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        implementTestList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        docMaintainList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deleteReqStudentBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        deleteImplementStudentBtn = new javax.swing.JButton();
        deleteDocStudentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Students");

        reqDesignList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = GroupGenerator.students.getDesignReqNames();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(reqDesignList);

        implementTestList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = GroupGenerator.students.getImplementTestNames();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(implementTestList);

        docMaintainList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = GroupGenerator.students.getDocMaintainNames();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(docMaintainList);

        jLabel2.setText("Requirements/Design");

        jLabel3.setText("Implementation/Testing");

        jLabel4.setText("Documentation/Maintenance");

        deleteReqStudentBtn.setText("Delete Student");
        deleteReqStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReqStudentBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        deleteImplementStudentBtn.setText("Delete Student");
        deleteImplementStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteImplementStudentBtnActionPerformed(evt);
            }
        });

        deleteDocStudentBtn.setText("Delete Student");
        deleteDocStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDocStudentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deleteReqStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(deleteImplementStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteDocStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteReqStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteImplementStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDocStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteReqStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReqStudentBtnActionPerformed
        if (reqDesignList.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a student from the Requirements/Design List");
        }
        else{
          MainMenu.groupGenerator.students.removeStudent(reqDesignList.getSelectedIndex(), 1); 
          JOptionPane.showMessageDialog(null, "Student Deleted");
          refreshLists();
        } 
    }//GEN-LAST:event_deleteReqStudentBtnActionPerformed

    private void deleteImplementStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteImplementStudentBtnActionPerformed
        if (implementTestList.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a student from the Implementation/Test List");
        } else {
            MainMenu.groupGenerator.students.removeStudent(implementTestList.getSelectedIndex(), 2);
            JOptionPane.showMessageDialog(null, "Student Deleted");
            refreshLists();
        }
    }//GEN-LAST:event_deleteImplementStudentBtnActionPerformed

    private void deleteDocStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDocStudentBtnActionPerformed
        if (docMaintainList.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a student from the Documentation/Maintenance List");
        } else {
            MainMenu.groupGenerator.students.removeStudent(docMaintainList.getSelectedIndex(), 3);
            JOptionPane.showMessageDialog(null, "Student Deleted");
            refreshLists();
        }
    }//GEN-LAST:event_deleteDocStudentBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteDocStudentBtn;
    private javax.swing.JButton deleteImplementStudentBtn;
    private javax.swing.JButton deleteReqStudentBtn;
    private javax.swing.JList<String> docMaintainList;
    private javax.swing.JList<String> implementTestList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> reqDesignList;
    // End of variables declaration//GEN-END:variables
}
